#!/usr/bin/env bash

set -euo pipefail

command=()

for arg in "$@"; do
  case "$arg" in
    "--") shift; break ;;
    *) command+=("$arg"); shift ;;
  esac
done

body="$@"
if [[ ! -z "$body" ]]; then
  body=$(printf "\n%s" "$body")
fi

script=$(sd which "${command[@]}")

if [[ -e "$script" ]]; then
  echo "$script already exists!" >&2
  exit 1
fi

mkdir -p "$(dirname "$script")"
cat > "$script" <<EOF
#!/usr/bin/env bash

set -euo pipefail
$body
EOF

chmod +x "$script"

if [[ -z "$body" ]]; then
  sd edit "${command[@]}"
fi
