#!/usr/bin/env bash

# create a new script and open it for editing

set -euo pipefail

command=()

for arg in "$@"; do
  case "$arg" in
    "--") shift; break ;;
    *) command+=("$arg"); shift ;;
  esac
done

sd "${command[@]}" --new "$@"
